### ISSUE TITLE
Can't exit from ssh password prompt

### ISSUE THREAD

**Issue by smahood** [epiccastle/spire#11]
When prompted for a password on the initial ssh connection, I can't find any way to exit the prompt - in particular, Ctrl-C doesn't work.
Running on Ubuntu 16.04.6

**Comment by borkdude** [comment]
I noticed this too. Pressing enter and then Ctrl-C worked for me.

**Comment by smahood** [comment]
I managed to get it to work consistently by pressing Ctrl-C, then enter, then Ctrl-C again.

**Comment by retrogradeorbit** [comment]
released in https://github.com/epiccastle/spire/releases/tag/v0.1.0-alpha.2
