### ISSUE TITLE
[shell module] :ok-exit doesn't affect result

### ISSUE THREAD

**Issue by tomconnors** [epiccastle/spire#126]
Looks like the :ok-exit option of the shell module doesn't affect the result. Here's an example:
``` bash
spire --version
# Version: 0.1.0-alpha.15
spire -e '(ssh "ubuntu@10.10.3.115" (shell {:cmd "echo foo" :ok-exit (fn [code] false)}))'
```
This will have `:result :ok` despite :ok-exit always returning false.

**Comment by retrogradeorbit** [comment]
released in v0.1.0-alpha.17
