### ISSUE TITLE
Make modules recognize the OS

### ISSUE THREAD

**Issue by zilti** [epiccastle/spire#19]
It is not possible to use the "service" module for FreeBSD guests because it expects systemd. There should be a mechanism so modules can act differently depending on the OS.

**Comment by retrogradeorbit** [comment]
yes! the service module needs to recognise the OS. There is a macro to facilitate this `spire.facts/on-os` but the service module has not been adapted to use it on freeBSD... yet.

**Comment by retrogradeorbit** [comment]
released in https://github.com/epiccastle/spire/releases/tag/v0.1.0-alpha.2
