### ISSUE TITLE
Is it possible to 'import' or 'load' one .clj into another?

### ISSUE THREAD

**Issue by gleisonsilva** [epiccastle/spire#24]
Hello!

Suposed that I have hosts.clj e systems.clj is it possible to require hosts.clj in systems.clj?

Tks

**Comment by retrogradeorbit** [comment]
For evaluating clojure code and defining functions? Not at the moment. But it is planned. 

For the concept of "hosts" or "systems" you can use the reader to parse eden formatted content from a file.

## For example:

### hosts.edn
```clojure
{:host1 {:host-string "root@host1"
         :key :host1}
 :host2 {:host-string "root@host2"
         :key :host2}
 :localhost {:host-string "localhost"
             :key :localhost}}
```

### load it
```shell
$ spire -e '(clojure.edn/read-string (slurp "hosts.edn"))'
{:host1 {:host-string "root@host1", :key :host1},
 :host2 {:host-string "root@host2", :key :host2},
 :localhost {:host-string "localhost", :key :localhost}}
```
## Another example

### example.clj 
```clojure
#!/usr/bin/env spire

(require '[clojure.edn :as edn])

(def hosts (edn/read-string (slurp "hosts.edn")))

(ssh (:localhost hosts)
     (get-fact))
```

### running
```shell
$ chmod a+x example.clj 
$ ./example.clj 
{:paths { ...
```

**Comment by retrogradeorbit** [comment]
ticket for `require` and `import` implementation in #25

**Comment by gleisonsilva** [comment]
Tks for the fast reply. I'll use this tip.
