### ISSUE TITLE
(upload :preserve true) can give an unexpected error

### ISSUE THREAD

**Issue by jeroenvandijk** [epiccastle/spire#69]
Trying to upload dir `deployment/docker` with:

```clojure
(upload {:dest "deployment"
         :src "../deployment/docker"
         :recurse true
         :preserve false
         })
```
This has given me the following message “Assert failed: attribute tree must be passed a directory”. 

When I set `:preserve false` this error goes away. In both cases the upload succeeds.

**Comment by retrogradeorbit** [comment]
fixed in 0.1.0-alpha.13
