### ISSUE TITLE
Error using java.time.Instant

### ISSUE THREAD

**Issue by tomconnors** [epiccastle/spire#71]
There appears to be a problem constructing java.time.Instant obects with the `now` method.

`spire -e '(debug (java.time.Instant/now))'`  gives "No matching method now found taking 0 args", from `sci.impl.Reflector.invokeMatchingMethod(Reflector.java:109)`.

Borkdude pointed out on slack that this works w/ babashka.

**Comment by retrogradeorbit** [comment]
a missing graal reflection config.

**Comment by retrogradeorbit** [comment]
appears to have been fixed in c927a11

**Comment by retrogradeorbit** [comment]
fixed in 0.1.0-alpha.13
