### ISSUE TITLE
Difficulties w/ line-in-file module

### ISSUE THREAD

**Issue by tomconnors** [epiccastle/spire#84]
I'm attempting to use line-in-file to add a known_hosts key for cloning repos from github. I hit a few snags:

- line-in-file doesn't modify the file when it's completely empty. I had to manually add a blank line to the file, then line-in-file would work correctly.
- the regex support can be difficult to use. In my use case, I want to check whether an exact line is present in the file. The line contains regex special characters, so it doesn't match itself when converted to a regex. In java-land, I can fix that by quoting the regex w/ java.util.regex.Pattern.quote, but that doesn't translate to the same thing when the regex is converted to sed syntax.

Ideas:
- Allow :regexp to be a string, and convert it to a regex that will only match that string.
- When :regexp isn't provided, convert :line to a regex that will only match :line, and use that.
- Document that the module doesn't actually use java regular expressions

**Comment by retrogradeorbit** [comment]
Good ideas @tomconnors ! Will add tickets

**Comment by retrogradeorbit** [comment]
this is all implemented in v0.1.0-alpha.15

**Comment by tomconnors** [comment]
After updating to latest spire, I'm still seeing line-in-file fail to add a line to a totally empty file.
