### ISSUE TITLE
Failed with Fish shell on remote

### ISSUE THREAD

**Issue by PrestanceDesign** [epiccastle/spire#9]
Hi!

I just tried your awesome tool and I notice it fails when remote use Fish shell.

Stacktrace:
`Exception in thread "main" clojure.lang.ExceptionInfo: No matching field found: getMessage for class java.lang.NullPointerException [at line 1, column 1] {:type :sci/error, :row 1, :col 1, :message "No matching field found: getMessage for class java.lang.NullPointerException [at line 1, column 1]"}`

Best regards.

**Comment by retrogradeorbit** [comment]
Thanks for trying it out! Can I have the full stack trace?

**Comment by retrogradeorbit** [comment]
you could be experiencing https://github.com/epiccastle/spire/issues/10

Try latest release and see if it resolves the problem

**Comment by PrestanceDesign** [comment]
> Try latest release and see if it resolves the problem

I try the latest release and same error.
[stacktrace.txt](https://github.com/epiccastle/spire/files/4254124/stacktrace.txt)

**Comment by retrogradeorbit** [comment]
Have recreated the error.

**Comment by retrogradeorbit** [comment]
released in https://github.com/epiccastle/spire/releases/tag/v0.1.0-alpha.2

@PrestanceDesign please test when you get a chance

**Comment by PrestanceDesign** [comment]
Yeah, thx for this release.
It works nice!
